### ISSUE TITLE
Joining your team excites me as it would allow me to apply my extensive experience to further your projects’ success.

### ISSUE THREAD

**Issue by johnsmith0212** [NFT-Social-Credit-System/rscs-app#9]
Hi, I'm Ethan Tan, a web full-stack and blockchain developer with extensive experience spanning over 8 years. I specialize in developing resilient, scalable web applications and state-of-the-art blockchain solutions. My expertise in frameworks like React.js, Vue.js, and Next.js, along with my proficiency in Solidity for smart contract development, ensures I deliver premium, secure, and efficient solutions tailored to your specific needs.

**Comment by MidpriceDog** [comment]
This project has been abandoned for the time being. Thanks.

**Comment by johnsmith0212** [comment]
If you need developer, plz contact me

-Contact Info
skype: https://join.skype.com/invite/FVUI6gLcYgAE
telegram: https://t.me/ethantan1116
slack: https://join.slack.com/t/ksc-xme4972/shared_invite/zt-2ld45idp2-G9HkxP_wX4ctwQshyPM7Ig
discord: https://discord.gg/VxnfdY4bS4
